### ISSUE TITLE
README, Testes, etc

### ISSUE THREAD

**Issue by pbassut** [mundipagg/mundipagg-one-python#1]
Acho que a biblioteca está faltando bastante coisa básica pra qualquer repositório.
* Como usar;
* Alguns testes pra ver o negócio funcionando pelo menos em sandbox;
* O que a lib suporta até então;

**Comment by vandrade-mundipagg** [comment]
Olá Patrick!

Você chegou a olhar a nossa seção [Wiki](https://github.com/mundipagg/mundipagg-one-python/wiki)? Lá tem os exemplos de utilização com os snippets.

**Comment by pbassut** [comment]
Não tinha visto. Então podia ter no readme que a doc está no wiki.

**Comment by vandrade-mundipagg** [comment]
Sim sim, antes de te responder eu adicionei um link para a Wiki no nosso readme. Obrigado pelo feedback!

**Comment by pbassut** [comment]
Valeu!
