### ISSUE TITLE
Adicionar SmartWalletKey no header das requisições

### ISSUE THREAD

**Issue by matheusjardimb** [mundipagg/mundipagg-one-python#4]
Estou analisando a implementação de split de pagamentos e analisando o código não encontrei uma forma de incluir o SmartWalletKey.

Estou enganado ou essa funcionalidade não está implementada?

**Comment by avirzin** [comment]
Me falaram que a funcionalidade de _split_ de pagamentos só tem previsão de aparecer em fev/2017.

**Comment by agaldino** [comment]
Opa @matheusjardimb  como o @avirzin falou, a previsão dessa funcionalidade é para o mês de Fevereiro. Assim que tivermos a funcionalidade na nossa API vamos atualizar todas as SDKs para dar suporte.
Sendo assim, vou fechar o Issue.
